"""
render_distortion_foreshort.py

Renders foreshortening distortion sequences generated by gen_distortion_foreshort.py.

For each distortion_foreshortening_<target>/ folder:
  - Loads scene.json into AI2THOR
  - Teleports camera to each orbit pose in camera_poses.json
  - Saves view_000.png (reference) through view_N.png (orbit angles)

Usage:
  python render_distortion_foreshort.py \
      --scene-dir /path/to/distortion_foreshortening_ottoman-0_bedroom/
      [--out-dir /path/to/output]   # default: <scene-dir>/multiview/
      [--port 8200]

  # Or batch over a whole scene folder:
  python render_distortion_foreshort.py \
      --scene-dir /path/to/distortion_scenes_layout/a_bedroom-.../
      [--port 8200]
"""

import os
import sys
import json
import argparse
import time
from pathlib import Path

import numpy as np
from PIL import Image

import ai2thor.wsgi_server
from ai2thor.controller import Controller
from ai2thor.hooks.procedural_asset_hook import ProceduralAssetHookRunner

import compress_json

from ai2holodeck.constants import THOR_COMMIT_ID, OBJATHOR_ASSETS_DIR


# ── helpers ────────────────────────────────────────────────────────────────────

def _save_png(path: str, frame):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if isinstance(frame, np.ndarray):
        Image.fromarray(frame).save(path)
    else:
        Image.fromarray(np.array(frame)).save(path)


def _create_controller(port: int, asset_dir: str) -> Controller:
    for attempt in range(1, 6):
        try:
            return Controller(
                commit_id=THOR_COMMIT_ID,
                start_unity=False,
                port=port,
                scene="Procedural",
                gridSize=0.25,
                width=1024,
                height=1024,
                server_class=ai2thor.wsgi_server.WsgiServer,
                makeAgentsVisible=False,
                visibilityScheme="Distance",
                renderDepthImage=False,
                action_hook_runner=ProceduralAssetHookRunner(
                    asset_directory=asset_dir,
                    asset_symlink=True,
                    verbose=False,
                ),
            )
        except OSError as e:
            if "Address already in use" in str(e) and attempt < 5:
                print(f"[WARN] Port {port} in use, waiting 2s... ({attempt}/5)")
                time.sleep(2)
            else:
                raise


def _expected_view_png_paths(scene_dir: Path, out_dir: Path) -> list[Path] | None:
    """
    Return the list of multiview PNG paths this variant should produce.
    None if camera_poses.json is missing or has no frames.
    """
    cam_poses_path = scene_dir / "camera_poses.json"
    if not cam_poses_path.is_file():
        return None
    with open(cam_poses_path, encoding="utf-8") as f:
        cam_data = json.load(f)
    frames = cam_data.get("multiview", {}).get("frames", [])
    if not frames:
        return None
    paths: list[Path] = []
    for frame_info in frames:
        idx = frame_info.get("frame_idx")
        if not isinstance(idx, int):
            return None
        paths.append(out_dir / f"view_{idx:03d}.png")
    return paths


def _variant_fully_rendered(scene_dir: Path, out_dir: Path) -> bool:
    """True only when every expected view_*.png from camera_poses exists."""
    expected = _expected_view_png_paths(scene_dir, out_dir)
    if not expected:
        return False
    return all(p.is_file() for p in expected)


def _load_scene(scene_json_path: str) -> dict:
    """Load scene JSON (supports compress_json .json.gz too)."""
    try:
        return compress_json.load(scene_json_path)
    except Exception:
        with open(scene_json_path, encoding="utf-8", errors="replace") as f:
            return json.load(f)


def _teleport(controller, pos: dict, rot: dict, fov: float = 90.0) -> bool:
    """TeleportFull to a specific pose. Returns True on success.

    AI2THOR requires rotation.x=0; pitch is controlled via the horizon parameter.
    rotation.x from our camera_poses.json is used as the horizon value.
    """
    horizon = float(rot.get("x", 0))  # pitch stored in rotation.x
    for attempt in range(3):
        e = controller.step(
            action="TeleportFull",
            x=pos["x"], y=pos["y"], z=pos["z"],
            rotation={"x": 0, "y": rot["y"], "z": 0},
            horizon=horizon,
            standing=True,
            forceAction=True,
        )
        controller.step("Pass")
        if e.metadata.get("lastActionSuccess"):
            return True
        print(f"  [WARN] TeleportFull failed (attempt {attempt+1}/3): "
              f"{e.metadata.get('errorMessage', '?')}")
    return False


def _capture_frame(controller, pos: dict, rot: dict) -> np.ndarray:
    """
    Update third-party camera to pos/rot and return the frame as ndarray.
    Assumes AddThirdPartyCamera was already called.
    """
    controller.step(
        action="UpdateThirdPartyCamera",
        position=pos,
        rotation={"x": rot.get("x", 0), "y": rot["y"], "z": rot.get("z", 0)},
    )
    e = controller.step("Pass")

    if hasattr(e, "third_party_camera_frames") and e.third_party_camera_frames:
        return e.third_party_camera_frames[0]
    if hasattr(e, "thirdPartyCameraFrames") and e.thirdPartyCameraFrames:
        return e.thirdPartyCameraFrames[0]
    # fallback: agent camera
    print("  [WARN] Third-party camera unavailable, using agent camera")
    return e.frame


# ── per-variant renderer ───────────────────────────────────────────────────────

def render_variant(controller, scene_dir: Path, out_dir: Path, *, force: bool = False) -> bool:
    """
    Render one distortion_foreshortening_<target>/ variant.
    scene_dir must contain scene.json and camera_poses.json.
    """
    scene_json_path = scene_dir / "scene.json"
    cam_poses_path  = scene_dir / "camera_poses.json"

    if not scene_json_path.exists() or not cam_poses_path.exists():
        print(f"[SKIP] Missing scene.json or camera_poses.json in {scene_dir}")
        return False

    # Skip only when all frames from camera_poses.json already exist (partial runs are re-done).
    if not force and _variant_fully_rendered(scene_dir, out_dir):
        exp = _expected_view_png_paths(scene_dir, out_dir) or []
        print(f"[SKIP] Already fully rendered ({len(exp)} views) → {out_dir}")
        return True

    print(f"\n{'='*60}")
    print(f"Rendering: {scene_dir.name}")

    # Load camera poses
    with open(cam_poses_path) as f:
        cam_data = json.load(f)

    frames = cam_data.get("multiview", {}).get("frames", [])
    if not frames:
        print("[ERROR] No frames in camera_poses.json")
        return False

    distortion_info = cam_data.get("distortion", {})
    target_id  = distortion_info.get("target_id", "?")
    print(f"  Target: {target_id}")
    print(f"  Frames: {len(frames)} "
          f"(orbit angles: {distortion_info.get('orbit_angles_deg', [])})")

    # Load scene into THOR
    scene = _load_scene(str(scene_json_path))
    try:
        controller.reset()
    except Exception:
        pass
    for _ in range(3):
        controller.step("Pass")

    e = controller.step(action="CreateHouse", house=scene)
    if not e.metadata.get("lastActionSuccess", True):
        print(f"  [WARN] CreateHouse returned error: {e.metadata.get('errorMessage')}")

    for _ in range(5):
        controller.step("Pass")

    try:
        controller.step(action="SetUIEnabled", enabled=False)
    except Exception:
        pass

    # Teleport to frame-0 position first to initialize
    f0 = frames[0]
    ok = _teleport(controller, f0["position"], f0["rotation"])
    if not ok:
        print("  [ERROR] Initial TeleportFull failed, skipping variant")
        return False

    # Add third-party camera at frame-0 pose
    controller.step(
        action="AddThirdPartyCamera",
        position=f0["position"],
        rotation={"x": f0["rotation"].get("x", 0),
                  "y": f0["rotation"]["y"],
                  "z": f0["rotation"].get("z", 0)},
        fieldOfView=float(f0.get("fov", 90.0)),
    )
    controller.step("Pass")

    out_dir.mkdir(parents=True, exist_ok=True)

    saved_frames = []
    for frame_info in frames:
        idx  = frame_info["frame_idx"]
        pos  = frame_info["position"]
        rot  = frame_info["rotation"]
        fov  = float(frame_info.get("fov", 90.0))
        orbit_deg = frame_info.get("orbit_deg", 0)

        # Teleport agent to each orbit position
        ok = _teleport(controller, pos, rot)
        if not ok:
            print(f"  [SKIP] frame {idx} (orbit {orbit_deg}°): teleport failed")
            continue

        # Capture via third-party camera
        img = _capture_frame(controller, pos, rot)
        fname = f"view_{idx:03d}.png"
        _save_png(str(out_dir / fname), img)

        label = "ref" if orbit_deg == 0 else f"{orbit_deg}°"
        print(f"  [OK] view_{idx:03d}.png  ({label})")
        saved_frames.append({"frame_idx": idx, "orbit_deg": orbit_deg,
                              "image_file": fname,
                              "position": pos, "rotation": rot, "fov": fov})

    # Save a summary JSON alongside the images
    summary = {
        "target_id":   target_id,
        "distortion":  "foreshortening",
        "scene_dir":   str(scene_dir),
        "frames":      saved_frames,
    }
    with open(out_dir / "render_summary.json", "w") as f:
        json.dump(summary, f, indent=2)

    print(f"  [DONE] {len(saved_frames)} frames saved → {out_dir}")
    return len(saved_frames) > 0


# ── batch helpers ──────────────────────────────────────────────────────────────

def _find_variants(root: Path) -> list[Path]:
    """Find all distortion_*/ folders under root."""
    return sorted(p for p in root.rglob("distortion_*")
                  if p.is_dir() and (p / "camera_poses.json").exists())


# ── entry point ────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Render distortion sequences (foreshortening, size-distance, etc.).")
    group = parser.add_mutually_exclusive_group(required=True)
    group.add_argument(
        "--scene",
        help="Path to scene.json inside a distortion_foreshortening_*/ folder. "
             "camera_poses.json is loaded automatically from the same directory.",
    )
    group.add_argument(
        "--scene-dir",
        help="Path to a distortion_foreshortening_*/ folder OR a parent directory "
             "to batch-render all such folders within it.",
    )
    parser.add_argument(
        "--out-dir", default=None,
        help="Output directory for rendered images. "
             "Default: <variant_dir>/multiview/",
    )
    parser.add_argument("--asset-dir", default=OBJATHOR_ASSETS_DIR)
    parser.add_argument("--port", type=int, default=8200)
    parser.add_argument(
        "--force",
        action="store_true",
        help="Re-render even when all expected view_*.png files already exist.",
    )
    args = parser.parse_args()

    # Resolve scene_dir from either --scene or --scene-dir
    if args.scene:
        scene_path = Path(args.scene)
        if not scene_path.exists():
            print(f"[ERROR] Path not found: {scene_path}")
            sys.exit(1)
        if scene_path.is_dir():
            # User passed a directory — treat it as --scene-dir
            scene_dir = scene_path
        else:
            # User passed a scene.json file
            scene_dir = scene_path.parent
    else:
        scene_dir = Path(args.scene_dir)

    if not scene_dir.exists():
        print(f"[ERROR] Path not found: {scene_dir}")
        sys.exit(1)

    # Determine variants to render
    if (scene_dir / "camera_poses.json").exists():
        variants = [scene_dir]
    else:
        variants = _find_variants(scene_dir)
        if not variants:
            print(f"[ERROR] No distortion_foreshortening_*/ variants found under {scene_dir}")
            sys.exit(1)
        print(f"Found {len(variants)} variant(s) to render")

    print("\n[INFO] Connecting to AI2THOR (make sure Unity is running)...")
    controller = _create_controller(args.port, args.asset_dir)
    print("[OK] Controller connected")

    success = 0
    for variant_dir in variants:
        if args.out_dir and len(variants) == 1:
            out_dir = Path(args.out_dir)
        else:
            out_dir = variant_dir / "multiview"

        ok = render_variant(controller, variant_dir, out_dir, force=args.force)
        if ok:
            success += 1

    controller.stop()
    print(f"\n{'='*60}")
    print(f"Done. {success}/{len(variants)} variants rendered successfully.")


if __name__ == "__main__":
    main()
